/*
 * PasswordPrompt.java
 *
 * Created on Jan 19, 2011, 4:30:40 PM
 */

package org.mcwebmin.desktop;

import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author joe
 */
public class PasswordPrompt extends javax.swing.JDialog {

   private DataHandler connection;
   private final int COUNTDOWN_FROM = 15;
   private Countdown cd = new Countdown(COUNTDOWN_FROM);

    /** Creates new form PasswordPrompt */
    public PasswordPrompt(java.awt.Frame parent, boolean modal,DataHandler cxn) {
        super(parent, modal);
        Thread ctdn = new Thread(cd);
        ctdn.start();
        initComponents();
        updateCountdown(COUNTDOWN_FROM);
        connection = cxn;
        this.setVisible(true);
        passwordField.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      passwordField = new javax.swing.JPasswordField();
      jLabel1 = new javax.swing.JLabel();
      loginButton = new javax.swing.JButton();
      countdownLabel = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            passwordFieldKeyReleased(evt);
         }
      });

      jLabel1.setFont(new java.awt.Font("Arial", 1, 14));
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setText("Server Password");

      loginButton.setText("Log In");
      loginButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            loginButtonActionPerformed(evt);
         }
      });

      countdownLabel.setText("15");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(loginButton))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(countdownLabel)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(countdownLabel)
               .addComponent(jLabel1))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(loginButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_passwordFieldKeyReleased
    {//GEN-HEADEREND:event_passwordFieldKeyReleased
       if (evt.getKeyCode() == KeyEvent.VK_ENTER)
       {
          returnPass();
       }
    }//GEN-LAST:event_passwordFieldKeyReleased

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loginButtonActionPerformed
    {//GEN-HEADEREND:event_loginButtonActionPerformed
      returnPass();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void returnPass()
    {
       String password = "";
       for (char c : passwordField.getPassword())
       {
          password += c;
       }
       connection.send(password);
       cd.stop();
       this.dispose();
    }

    private class Countdown implements Runnable
    {
       private int countdown;
       private boolean keepRunning = true;
       public Countdown(int from)
       {
          if (from <= 0)
          {
             from = 1;
          }
          countdown = from;
       }
       public void stop()
       {
          keepRunning = false;
       }
      public void run()
      {
         while (countdown > 0 && keepRunning)
         {
            updateCountdown(countdown);
            countdown--;
            try {
               Thread.sleep(1000);
            } catch (InterruptedException ex) {
               Logger.getLogger(PasswordPrompt.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         if (keepRunning)
         {
            dispose();
            connection.handle(DataHandler.TIMEOUT);
         }
      }
    }

    private void updateCountdown(final int countdown)
    {
      SwingUtilities.invokeLater(new Runnable(){

         public void run()
         {
            if (countdownLabel != null)
            {
               countdownLabel.setText(String.valueOf(countdown));
            }
         }

      });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel countdownLabel;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JButton loginButton;
   private javax.swing.JPasswordField passwordField;
   // End of variables declaration//GEN-END:variables

}
